"""added indexes in blacklist table

Revision ID: 8ffc961ef4ef
Revises: 3200ffdffafc
Create Date: 2025-07-21 10:28:45.545807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ffc961ef4ef'
down_revision: Union[str, Sequence[str], None] = '3200ffdffafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklist_customers', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(
        'idx_blacklist_search_full',
        'blacklist_customers',
        ['last_name', 'first_name', 'middle_name'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blacklist_search_full', table_name='blacklist_customers')
    op.alter_column('blacklist_customers', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
